# Versioning
version: 1.0.0.{build}

# Configuration
# TODO: I'd like to enable 64-bit builds, but 64-bit cgo requires Mingw-w64,
# which isn't available on Appveyor.  64-bit Go is available however, in
# C:\go-x64, and is in the PATH by default (which is why we have to override
# PATH).
environment:
  GOROOT: C:\go-x86
  GOARCH: 386
  GOPATH: C:\projects

# Set up clone path
clone_folder: C:\projects\src\github.com\havoc-io\go-keytar

# Run build (just here to stop the default Visual Studio build)
build_script:
  - set PATH=%GOROOT%\bin;C:\MinGW\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go build

# Run tests
test_script:
  - set PATH=%GOROOT%\bin;C:\MinGW\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
