# Versioning
version: 1.0.0.{build}

# Configuration
# NOTE: Structure of MSYS2 installation outlined in this comment:
# http://help.appveyor.com/discussions/suggestions/615-support-for-msys2#comment_37571757
environment:
  GOROOT: C:\go
  GOPATH: C:\projects

  matrix:
  - GOARCH: 386
    MINGWROOT: C:\msys64\mingw32
  - GOARCH: amd64
    MINGWROOT: C:\msys64\mingw64

# Set up clone path
clone_folder: C:\projects\src\github.com\havoc-io\go-keytar

# Run build (just here to stop the default Visual Studio build)
build_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go build

# Run tests
test_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
