# Versioning
version: 1.0.0.{build}

# Configuration
environment:
  matrix:
  - GOPATH: C:\projects
    MINGWBIN: C:\MinGW\bin
    GOROOT: C:\go-x86
    GOARCH: 386
  - GOPATH: C:\projects
    MINGWBIN: C:\msys64\mingw64\bin
    GOROOT: C:\go
    GOARCH: amd64

# Set up clone path
clone_folder: C:\projects\src\github.com\havoc-io\go-keytar

# Run build (just here to stop the default Visual Studio build)
build_script:
  - set PATH=%MINGWBIN%;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go build

# Run tests
test_script:
  - set PATH=%MINGWBIN%;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
