# Versioning
version: 1.0.0.{build}

# Configuration
environment:
  GOVERSION: 1.5.1
  GOROOT: C:\go
  GOPATH: C:\projects

  matrix:
  - GOARCH: 386
    MINGWROOT: C:\MinGW
  - GOARCH: amd64
    MINGWROOT: C:\msys64\mingw64

# Set up clone path
clone_folder: C:\projects\src\github.com\havoc-io\go-keytar

# Install dependencies (an upgraded Go version)
install:
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.zip
  - 7z x go%GOVERSION%.windows-%GOARCH%.zip -oC:\ >nul

# Run build (just here to stop the default Visual Studio build)
build_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go build

# Run tests
test_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %GOPATH%\src\github.com\havoc-io\go-keytar
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
