# Versioning
version: 1.0.0.{build}

# Configuration
# TODO: I'd like to figure out a way to use a build matrix here to support both
# C:\go-x64 and C:\go-x86, but we can't use the GOPATH environment variable in
# the clone_folder setting, so I'm not sure how to do this
environment:
  GOPATH: C:\go-x64

# Set up clone path
clone_folder: C:\go-x64\src\github.com\havoc-io\go-keytar

# Run tests
test_script:
  - cd C:\go-x64\src\github.com\havoc-io\go-keytar
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
